apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fldp
  name: np
spec:
  ports:
  - name: 80-80
    nodePort: 30003
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: fldp
  type: NodePort
status:
  loadBalancer: {}
